[package]
name = "web_search_providers"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/web_search_providers.rs"

[dependencies]
hotpath = { path = "../../../hotpath-rs/crates/hotpath", features=['tokio','futures'] }

anyhow.workspace = true
client.workspace = true
cloud_llm_client.workspace = true
futures.workspace = true
gpui.workspace = true
http_client.workspace = true
language_model.workspace = true
serde.workspace = true
serde_json.workspace = true
web_search.workspace = true

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-mcp= ["hotpath/hotpath-mcp"]
hotpath-mcp-meta= ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]


