[package]
name = "sum_tree"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"
description = "A sum tree data structure, a concurrency-friendly B-tree"

[lints]
workspace = true

[lib]
path = "src/sum_tree.rs"
doctest = false

[dependencies]
channels-console = { version = "0.2", optional = true, features = ["futures"] }
hotpath = { version = "0.16", features = ["futures"] }
heapless.workspace = true
rayon.workspace = true
log.workspace = true
ztracing.workspace = true
tracing.workspace = true
proptest = { workspace = true, optional = true }

[dev-dependencies]
ctor.workspace = true
rand.workspace = true
proptest.workspace = true
zlog.workspace = true


[package.metadata.cargo-machete]
ignored = ["tracing"]

[features]
channels-console = ["dep:channels-console"]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-mcp = ["hotpath/hotpath-mcp"]
hotpath-mcp-meta = ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]
test-support = ["proptest"]