[package]
name = "project_benchmarks"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
channels-console = { version = "0.2", optional = true, features = ["futures"] }
hotpath = { version = "0.20", features = ["futures"] }
anyhow.workspace = true
askpass.workspace = true
clap.workspace = true
client.workspace = true
futures.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
http_client = { workspace = true, features = ["test-support"]}
language.workspace = true
node_runtime.workspace = true
project.workspace = true
release_channel.workspace = true
remote = { workspace = true, features = ["build-remote-server-binary"] }
rpassword = "7.4"
semver.workspace = true
settings.workspace = true
watch.workspace = true


[features]
channels-console = ["dep:channels-console"]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-mcp = ["hotpath/hotpath-mcp"]
hotpath-mcp-meta = ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]

[lints]
workspace = true
