[package]
name = "fs_benchmarks"
version = "0.1.0"
publish.workspace = true
edition.workspace = true

[dependencies]
channels-console = { version = "0.2", optional = true, features = ["futures"] }
hotpath = { version = "0.16", features = ["futures"] }
fs.workspace = true
gpui.workspace = true
gpui_platform.workspace = true


[features]
channels-console = ["dep:channels-console"]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-mcp = ["hotpath/hotpath-mcp"]
hotpath-mcp-meta = ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]

[lints]
workspace = true
