[package]
name = "panel"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/panel.rs"

[dependencies]
hotpath = { path = "../../../hotpath-rs/crates/hotpath", features=['tokio','futures'] }

editor.workspace = true
gpui.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
workspace.workspace = true

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-mcp= ["hotpath/hotpath-mcp"]
hotpath-mcp-meta= ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]


