[package]
name = "refineable"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"
description = "A macro for creating 'refinement' types that can be used to partially initialize or mutate a complex struct"

[lints]
workspace = true

[lib]
path = "src/refineable.rs"
doctest = false

[dependencies]
hotpath = { path = "../../../hotpath-rs/crates/hotpath", features=['tokio','futures'] }

derive_refineable.workspace = true

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-mcp= ["hotpath/hotpath-mcp"]
hotpath-mcp-meta= ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]

hotpath-off = ["hotpath/hotpath-off"]

