[package]
name = "open_path_prompt"
version = "0.1.0"
publish.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later"

[dependencies]
channels-console = { version = "0.2", optional = true, features = ["futures"] }
hotpath = { version = "0.20", features = ["futures"] }
file_icons.workspace = true
futures.workspace = true
fuzzy.workspace = true
gpui.workspace = true
picker.workspace = true
project.workspace = true
schemars.workspace = true
serde.workspace = true
settings.workspace = true
ui.workspace = true
util.workspace = true
workspace.workspace = true


[features]
channels-console = ["dep:channels-console"]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-mcp = ["hotpath/hotpath-mcp"]
hotpath-mcp-meta = ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]

[dev-dependencies]
editor = {workspace = true, features = ["test-support"]}
gpui = {workspace = true, features = ["test-support"]}
serde_json.workspace = true
theme = {workspace = true, features = ["test-support"]}
theme_settings.workspace = true
workspace = {workspace = true, features = ["test-support"]}

[lints]
workspace = true

[lib]
path = "src/open_path_prompt.rs"
