[package]
name = "rope"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/rope.rs"

[dependencies]
channels-console = { version = "0.2", optional = true, features = ["futures"] }
hotpath = { version = "0.20", features = ["futures"] }
heapless.workspace = true
log.workspace = true
rayon.workspace = true
sum_tree.workspace = true
unicode-segmentation.workspace = true
util.workspace = true
ztracing.workspace = true
tracing.workspace = true


[features]
channels-console = ["dep:channels-console"]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-alloc-meta = ["hotpath/hotpath-alloc-meta"]
hotpath-cpu = ["hotpath/hotpath-cpu"]
hotpath-mcp = ["hotpath/hotpath-mcp"]
hotpath-mcp-meta = ["hotpath/hotpath-mcp-meta"]
hotpath-meta = ["hotpath/hotpath-meta"]

[dev-dependencies]
ctor.workspace = true
gpui = { workspace = true, features = ["test-support"] }
rand.workspace = true
util = { workspace = true, features = ["test-support"] }
criterion.workspace = true
zlog.workspace = true

[[bench]]
name = "rope_benchmark"
harness = false

[package.metadata.cargo-machete]
ignored = ["tracing"]
