[package]
name = "component"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/component.rs"

[dependencies]
hotpath = { path = "../../../hotpath-rs/crates/hotpath", features=['tokio','futures'] }

collections.workspace = true
gpui.workspace = true
inventory.workspace = true
parking_lot.workspace = true
strum.workspace = true
theme.workspace = true

[dev-dependencies]
documented.workspace = true

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-meta = ["hotpath/hotpath-meta"]

hotpath-off = ["hotpath/hotpath-off"]

default = []
